### ISSUE TITLE
[Bug] GitHub Actions에서 echo 사용 시 BCrypt 해시 값의 $ 기호 손실로 인한 로그인 실패

### ISSUE THREAD

**Issue by yooookm** [tennispark/Backend#62]
## 🐛 버그 설명

GitHub Secrets에 `application.yml` 전체 내용을 등록하고, GitHub Actions 워크플로우에서 다음과 같이 `echo`를 사용해 파일을 생성했을 때,
BCrypt 해시 값 내부의 `$` 기호가 손실되어 서버에서 로그인 시 오류가 발생했습니다.

```yaml
- name: Make application.yml
  run: |
    echo "${{ secrets.PROPERTIES }}" > src/main/resources/application.yml
```

이 방식은 `$2a$...` 형식의 BCrypt 해시에서 `$` 기호를 쉘이 변수로 인식하여 제거해버리기 때문에,
최종적으로 생성된 `application.yml`에 저장된 패스워드 문자열은 **BCrypt 형식이 아닌 깨진 문자열**이 되었고,
이에 따라 다음과 같은 에러가 서버 로그에 발생했습니다

```
Encoded password does not look like BCrypt
```

로컬에서는 직접 `.yml` 파일을 작성해 실행했기 때문에 문제가 발생하지 않았고, 배포 서버에서만 오류가 발생한 상황입니다.

---

 ## 📁 파일 이름

* `.github/workflows/deploy.yml`

---

## 🔁 버그 재현 방법

1. GitHub Secrets에 `application.yml` 전체 내용을 등록 (BCrypt 해시 포함)
2. 워크플로우에서 `echo "${{ secrets.PROPERTIES }}"` 로 `application.yml` 생성
3. `main` 브랜치에 머지하거나 PR을 통해 CI/CD 실행
4. 서버에 배포된 `application.yml`에서 `$` 기호가 제거된 잘못된 해시 값이 저장됨
5. 로그인 시도 시 Spring Security에서 다음과 같은 오류 발생:

   ```
   Encoded password does not look like BCrypt
   ```

---

## ✅ 해결 방법

echo에서 오류가 나지 않도록  secrets.PROPERTIES을 Base64로 인코딩해서 넣었습니다.
이후 도커 스크립트에서는 해당 값을 base64 디코딩 후 사용합니다.
```
      - name: Make application.yml
        shell: bash
        env:
          APP_B64: ${{ secrets.PROPERTIES}}
        run: |
          mkdir -p src/main/resources
          echo "$APP_B64" | base64 --decode > src/main/resources/application.yml
```
